version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: conda run --no-capture-output -n comedy-project-docker python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/audio-annonation
      - D:/anaconda-envs:/envs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      # vector_db:
      #   condition: service_started
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    
    ports:
    - "5432:5432"

    env_file:
      - .env
    environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile.migrate
    command: conda run --no-capture-output -n comedy-project-docker python manage.py migrate
    volumes:
      - .:/audio-annonation
      - D:/anaconda-envs:/envs
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env



  # vector_db:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - vector_data:/qdrant/storage

volumes:
  postgres_data:
  # vector_data: