# Generated by Django 4.2.1 on 2023-06-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audio_file',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AudioAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('annotation', models.CharField(choices=[('speech', 'Speech'), ('music', 'Music'), ('noise', 'Noise'), ('laughter', 'Laughter'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='waveform_audio.audiofile')),
            ],
            options={
                'db_table': 'audio_annotation',
                'ordering': ['start_time', 'end_time'],
            },
        ),
    ]
