# Generated by Django 5.1 on 2024-08-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(unique=True, upload_to="audio/")),
                ("file_hash", models.CharField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audio File",
                "verbose_name_plural": "Audio Files",
                "db_table": "audio_file",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AudioAnnotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DurationField()),
                ("end_time", models.DurationField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.CharField(
                        help_text="Annotation label of the audio segment",
                        max_length=255,
                    ),
                ),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waveform_audio.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Annotation",
                "verbose_name_plural": "Audio Annotations",
                "db_table": "audio_annotation",
                "ordering": ["start_time", "end_time"],
                "unique_together": {
                    ("audio_file", "start_time", "end_time", "content")
                },
            },
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DurationField()),
                ("end_time", models.DurationField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(help_text="Subtitle content")),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waveform_audio.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtitle",
                "verbose_name_plural": "Subtitles",
                "db_table": "subtitle",
                "ordering": ["start_time", "end_time"],
                "unique_together": {("audio_file", "start_time", "end_time")},
            },
        ),
    ]
