# Generated by Django 5.0 on 2024-08-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(unique=True, upload_to="audio/")),
                ("file_hash", models.CharField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audio File",
                "verbose_name_plural": "Audio Files",
                "db_table": "audio_file",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AudioAnnotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "annotation",
                    models.CharField(
                        choices=[
                            ("speech", "Speech"),
                            ("music", "Music"),
                            ("noise", "Noise"),
                            ("laughter", "Laughter"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="waveform_audio.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Annotation",
                "verbose_name_plural": "Audio Annotations",
                "db_table": "audio_annotation",
                "ordering": ["start_time", "end_time"],
            },
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DurationField()),
                ("end_time", models.DurationField()),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="waveform_audio.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtitle",
                "verbose_name_plural": "Subtitles",
                "db_table": "subtitle",
                "ordering": ["start_time", "end_time"],
                "unique_together": {("audio_file", "start_time", "end_time")},
            },
        ),
    ]
