# Generated by Django 4.2.1 on 2023-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveform_audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(db_index=True, upload_to='audio/'),
        ),
    ]
