# Generated by Django 5.0 on 2024-07-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waveform_audio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="waveform_audio.audiofile",
                    ),
                ),
            ],
            options={
                "db_table": "subtitle",
                "ordering": ["start_time", "end_time"],
            },
        ),
    ]
