# Generated by Django 5.1 on 2024-08-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waveform_audio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audioannotation",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="subtitle",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
