# Generated by Django 5.0 on 2024-07-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waveform_audio", "0003_rename_text_subtitle_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitle",
            name="end_time",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="start_time",
            field=models.DurationField(),
        ),
    ]
